// =============================================================================
// SCAFFOLD AGENT - Lays the foundation before AI builds
// =============================================================================

import * as fs from 'fs';
import * as path from 'path';
import { GOLDEN_COMPONENTS } from '../../agent-runner/lib/golden-components';

/**
 * Generate scaffold structure - creates directories and skeleton files
 * This ensures the project structure exists BEFORE AI starts coding
 */
export function generateScaffold(repoPath: string): void {
  console.log("🏗️ SCAFFOLD: Laying the foundation...");
  
  // 1. Tvinga strukturen
  const dirs = [
    'src/app',
    'src/lib',
    'src/components/ui',
    'src/types',
    'backend'
  ];
  
  dirs.forEach(dir => {
    const fullPath = path.join(repoPath, dir);
    if (!fs.existsSync(fullPath)) {
      fs.mkdirSync(fullPath, { recursive: true });
      console.log(`   📁 Created directory: ${dir}`);
    }
  });
  
  // 2. Skapa kritiska "Skeleton Files" (så AI vet att de finns)
  const skeletonFiles: Record<string, string> = {
    'src/app/layout.tsx': `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'App',
  description: 'Generated by Frost Night Factory',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
    
    'src/app/page.tsx': `export default function Page() {
  return (
    <div className="min-h-screen flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold mb-4">Welcome</h1>
        <p className="text-gray-600">Page skeleton - AI will fill this in</p>
      </div>
    </div>
  );
}`,
    
    'src/app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  padding: 0;
}`,
    
    'src/lib/types.ts': `// Type Definitions
export type ID = string;
export type Timestamp = string;
`,
  };
  
  Object.entries(skeletonFiles).forEach(([file, content]) => {
    const p = path.join(repoPath, file);
    const dir = path.dirname(p);
    
    // Ensure directory exists
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    
    // Always ensure placeholder exists (create if missing, or if file is suspiciously small/empty)
    if (!fs.existsSync(p)) {
      fs.writeFileSync(p, content);
      console.log(`   📄 Created skeleton file: ${file}`);
    } else {
      // If file exists but is suspiciously small or empty, recreate it
      const stats = fs.statSync(p);
      if (stats.size < 50) {
        console.log(`   🔄 Recreating suspiciously small skeleton file: ${file}`);
        fs.writeFileSync(p, content);
      }
    }
  });
  
  // 3. Injicera Golden Components direkt (så de finns i registret)
  const uiDir = path.join(repoPath, 'src/components/ui');
  if (!fs.existsSync(uiDir)) {
    fs.mkdirSync(uiDir, { recursive: true });
  }
  
  Object.entries(GOLDEN_COMPONENTS).forEach(([name, content]) => {
    const componentPath = path.join(uiDir, name);
    if (!fs.existsSync(componentPath)) {
      fs.writeFileSync(componentPath, content);
      console.log(`   ✨ Injected Golden Component: ${name}`);
    }
  });
  
  console.log("✅ Scaffold complete. File structure enforced.");
}

/**
 * Generate Component Registry - scans project and creates a map of available components
 * This helps AI know what components exist and how to import them
 */
export function generateComponentRegistry(repoPath: string): Record<string, string> {
  const registry: Record<string, string> = {};
  
  function scan(dir: string, aliasBase: string) {
    if (!fs.existsSync(dir)) return;
    
    try {
      const files = fs.readdirSync(dir);
      files.forEach(f => {
        if (f.endsWith('.tsx') || f.endsWith('.ts')) {
          const name = f.replace(/\.(tsx|ts)$/, '');
          // Extract component name (capitalize first letter)
          const componentName = name.charAt(0).toUpperCase() + name.slice(1);
          registry[componentName] = `${aliasBase}/${name}`;
        }
      });
    } catch (e) {
      // Directory might not exist yet, skip silently
    }
  }
  
  // Scan UI components
  scan(path.join(repoPath, 'src/components/ui'), '@/components/ui');
  
  // Scan general components
  scan(path.join(repoPath, 'src/components'), '@/components');
  
  // Scan lib components
  scan(path.join(repoPath, 'src/lib'), '@/lib');
  
  return registry;
}

/**
 * Format Component Registry as a readable string for AI prompts
 */
export function formatComponentRegistry(registry: Record<string, string>): string {
  if (Object.keys(registry).length === 0) {
    return 'No components found in registry.';
  }
  
  const entries = Object.entries(registry)
    .map(([name, importPath]) => `  - ${name}: import { ${name} } from '${importPath}';`)
    .join('\n');
  
  return `AVAILABLE COMPONENTS (USE THESE IMPORTS):\n${entries}\n\nRULE: If a component exists in this list, IMPORT IT. Do not recreate it.`;
}

