// =============================================================================
// SCAFFOLD AGENT - Lays the foundation before AI builds
// =============================================================================
import * as fs from 'fs';
import * as path from 'path';
import { GOLDEN_COMPONENTS } from '../../agent-runner/lib/golden-components';
/**
 * Generate scaffold structure - creates directories and skeleton files
 * This ensures the project structure exists BEFORE AI starts coding
 */
export function generateScaffold(repoPath) {
    console.log("🏗️ SCAFFOLD: Laying the foundation...");
    // 1. Tvinga strukturen
    const dirs = [
        'src/app',
        'src/lib',
        'src/components/ui',
        'src/components/layout',
        'src/types',
        'backend'
    ];
    dirs.forEach(dir => {
        const fullPath = path.join(repoPath, dir);
        if (!fs.existsSync(fullPath)) {
            fs.mkdirSync(fullPath, { recursive: true });
            console.log(`   📁 Created directory: ${dir}`);
        }
    });
    // 2. Skapa kritiska "Skeleton Files" (så AI vet att de finns)
    const skeletonFiles = {
        'src/app/layout.tsx': `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'App',
  description: 'Generated by Frost Night Factory',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
        'src/app/page.tsx': `export default function Page() {
  return (
    <div className="min-h-screen flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold mb-4">Welcome</h1>
        <p className="text-gray-600">Page skeleton - AI will fill this in</p>
      </div>
    </div>
  );
}`,
        'src/app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  padding: 0;
}`,
        'src/lib/types.ts': `// Type Definitions
export type ID = string;
export type Timestamp = string;
`,
    };
    Object.entries(skeletonFiles).forEach(([file, content]) => {
        const p = path.join(repoPath, file);
        const dir = path.dirname(p);
        // Ensure directory exists
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }
        // Always ensure placeholder exists (create if missing, or if file is suspiciously small/empty)
        if (!fs.existsSync(p)) {
            fs.writeFileSync(p, content);
            console.log(`   📄 Created skeleton file: ${file}`);
        }
        else {
            // If file exists but is suspiciously small or empty, recreate it
            const stats = fs.statSync(p);
            if (stats.size < 50) {
                console.log(`   🔄 Recreating suspiciously small skeleton file: ${file}`);
                fs.writeFileSync(p, content);
            }
        }
    });
    // 3. ✅ V8.0: Inject Golden UI Components from templates/shadcn
    const goldenRoot = path.join(__dirname, '..', '..', 'agent-runner', 'templates', 'shadcn');
    // 3.1 Copy UI components
    const goldenUIDir = path.join(goldenRoot, 'components', 'ui');
    const projectUIDir = path.join(repoPath, 'src/components/ui');
    if (fs.existsSync(goldenUIDir)) {
        if (!fs.existsSync(projectUIDir)) {
            fs.mkdirSync(projectUIDir, { recursive: true });
        }
        const uiFiles = fs.readdirSync(goldenUIDir);
        uiFiles.forEach(file => {
            if (file.endsWith('.tsx') || file.endsWith('.ts')) {
                const sourcePath = path.join(goldenUIDir, file);
                const destPath = path.join(projectUIDir, file);
                // Only copy if doesn't exist (don't overwrite existing)
                if (!fs.existsSync(destPath)) {
                    fs.copyFileSync(sourcePath, destPath);
                    console.log(`   ✨ Injected Golden UI Component: ${file}`);
                }
            }
        });
    }
    // 3.2 Copy Layout components
    const goldenLayoutDir = path.join(goldenRoot, 'components', 'layout');
    const projectLayoutDir = path.join(repoPath, 'src/components/layout');
    if (fs.existsSync(goldenLayoutDir)) {
        if (!fs.existsSync(projectLayoutDir)) {
            fs.mkdirSync(projectLayoutDir, { recursive: true });
        }
        const layoutFiles = fs.readdirSync(goldenLayoutDir);
        layoutFiles.forEach(file => {
            if (file.endsWith('.tsx') || file.endsWith('.ts')) {
                const sourcePath = path.join(goldenLayoutDir, file);
                const destPath = path.join(projectLayoutDir, file);
                // Only copy if doesn't exist (don't overwrite existing)
                if (!fs.existsSync(destPath)) {
                    fs.copyFileSync(sourcePath, destPath);
                    console.log(`   ✨ Injected Golden Layout Component: ${file}`);
                }
            }
        });
    }
    // 3.3 Copy lib/utils.ts and lib/blueprints.ts
    const goldenLibDir = path.join(goldenRoot, 'lib');
    const projectLibDir = path.join(repoPath, 'src/lib');
    if (fs.existsSync(goldenLibDir)) {
        if (!fs.existsSync(projectLibDir)) {
            fs.mkdirSync(projectLibDir, { recursive: true });
        }
        const libFiles = ['utils.ts', 'blueprints.ts'];
        libFiles.forEach(file => {
            const sourcePath = path.join(goldenLibDir, file);
            const destPath = path.join(projectLibDir, file);
            if (fs.existsSync(sourcePath) && !fs.existsSync(destPath)) {
                fs.copyFileSync(sourcePath, destPath);
                console.log(`   ✨ Injected Golden Lib File: ${file}`);
            }
        });
    }
    // 3.4 Legacy: Still inject old GOLDEN_COMPONENTS if they exist (for backward compatibility)
    const uiDir = path.join(repoPath, 'src/components/ui');
    if (!fs.existsSync(uiDir)) {
        fs.mkdirSync(uiDir, { recursive: true });
    }
    // ✅ DEFENSIVE: Null check before Object.entries
    if (!GOLDEN_COMPONENTS || typeof GOLDEN_COMPONENTS !== 'object') {
        console.error('🚨 [Scaffold] GOLDEN_COMPONENTS is undefined or invalid!');
        console.error('   Type:', typeof GOLDEN_COMPONENTS);
        console.error('   Value:', GOLDEN_COMPONENTS);
        throw new Error('GOLDEN_COMPONENTS failed to import - check export syntax in golden-components.ts');
    }
    try {
        Object.entries(GOLDEN_COMPONENTS).forEach(([name, content]) => {
            if (typeof content !== 'string') {
                console.warn(`   ⚠️ Skipping ${name}: content is not a string`);
                return;
            }
            const componentPath = path.join(uiDir, name);
            if (!fs.existsSync(componentPath)) {
                fs.writeFileSync(componentPath, content);
                console.log(`   ✨ Injected Legacy Golden Component: ${name}`);
            }
        });
    }
    catch (error) {
        console.error('🚨 [Scaffold] Error injecting GOLDEN_COMPONENTS:', error.message);
        throw new Error(`Failed to inject golden components: ${error.message}`);
    }
    console.log("✅ Scaffold complete. File structure enforced.");
}
/**
 * Generate Component Registry - scans project and creates a map of available components
 * This helps AI know what components exist and how to import them
 */
export function generateComponentRegistry(repoPath) {
    const registry = {};
    function scan(dir, aliasBase) {
        if (!fs.existsSync(dir))
            return;
        try {
            const files = fs.readdirSync(dir);
            files.forEach(f => {
                if (f.endsWith('.tsx') || f.endsWith('.ts')) {
                    const name = f.replace(/\.(tsx|ts)$/, '');
                    // Extract component name (capitalize first letter)
                    const componentName = name.charAt(0).toUpperCase() + name.slice(1);
                    registry[componentName] = `${aliasBase}/${name}`;
                }
            });
        }
        catch (e) {
            // Directory might not exist yet, skip silently
        }
    }
    // Scan UI components
    scan(path.join(repoPath, 'src/components/ui'), '@/components/ui');
    // Scan general components
    scan(path.join(repoPath, 'src/components'), '@/components');
    // Scan lib components
    scan(path.join(repoPath, 'src/lib'), '@/lib');
    return registry;
}
/**
 * Format Component Registry as a readable string for AI prompts
 */
export function formatComponentRegistry(registry) {
    if (Object.keys(registry).length === 0) {
        return 'No components found in registry.';
    }
    const entries = Object.entries(registry)
        .map(([name, importPath]) => `  - ${name}: import { ${name} } from '${importPath}';`)
        .join('\n');
    return `AVAILABLE COMPONENTS (USE THESE IMPORTS):\n${entries}\n\nRULE: If a component exists in this list, IMPORT IT. Do not recreate it.`;
}
