// =============================================================================
// TYPE REGISTRY - Central registry of all types available in the codebase
// =============================================================================
// AI should reference this before generating imports
// Auto-generated by: npm run update-type-registry

/**
 * Central registry of all types available in the codebase
 * Format: { typeName: { from: modulePath, kind: 'interface' | 'type' } }
 */
export const TYPE_REGISTRY = {
  // Domain types (common)
  'Invoice': { from: './types', kind: 'interface' },
  'InvoiceLineItem': { from: './types', kind: 'interface' },
  'ExtractionResult': { from: './types', kind: 'interface' },
  'User': { from: './types', kind: 'interface' },
  'Product': { from: './types', kind: 'interface' },
  'Order': { from: './types', kind: 'interface' },
  
  // Utility types
  'ApiResponse': { from: './types', kind: 'type' },
  'ErrorResponse': { from: './types', kind: 'type' },
  'ID': { from: './types', kind: 'type' },
  'Timestamp': { from: './types', kind: 'type' },
  
  // UI Component Props
  'ButtonProps': { from: '@/components/ui/button', kind: 'interface' },
  'CardProps': { from: '@/components/ui/card', kind: 'interface' },
  'InputProps': { from: '@/components/ui/input', kind: 'interface' },
  'BadgeProps': { from: '@/components/ui/badge', kind: 'interface' },
} as const;

/**
 * Generate import statement for a type
 */
export function getImportForType(typeName: string): string | null {
  const entry = TYPE_REGISTRY[typeName as keyof typeof TYPE_REGISTRY];
  if (!entry) return null;
  
  return `import type { ${typeName} } from '${entry.from}';`;
}

/**
 * Get all types from a module
 */
export function getTypesFromModule(modulePath: string): string[] {
  return Object.entries(TYPE_REGISTRY)
    .filter(([_, meta]) => meta.from === modulePath)
    .map(([name]) => name);
}

/**
 * Check if a type exists in registry
 */
export function typeExists(typeName: string): boolean {
  return typeName in TYPE_REGISTRY;
}

/**
 * Get all available types as formatted string for AI prompts
 */
export function getTypeRegistryPrompt(): string {
  return Object.entries(TYPE_REGISTRY)
    .map(([name, meta]) => `- ${name}: import type { ${name} } from '${meta.from}';`)
    .join('\n');
}

