// =============================================================================
// VISUAL PRE-FLIGHT - Verify CSS/layout/page before build
// =============================================================================
// Ensures all critical files exist and have proper content before building
// Prevents 404s and Windows 95-looking pages

import * as fs from 'fs';
import * as path from 'path';

interface PreFlightCheck {
  name: string;
  status: 'pass' | 'fail' | 'fixed';
  message: string;
}

interface PreFlightResult {
  passed: boolean;
  checks: PreFlightCheck[];
  criticalFixes: number;
}

// Golden Templates for critical files
const GOLDEN_GLOBALS_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #0a0a0a;
  --foreground: #ededed;
}

html {
  color-scheme: dark;
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
`;

const GOLDEN_LAYOUT = `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'App',
  description: 'Generated by Frost Night Factory',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-screen bg-zinc-950 text-white antialiased">
        {children}
      </body>
    </html>
  );
}
`;

const GOLDEN_PAGE = `export default function Page() {
  return (
    <main className="min-h-screen flex items-center justify-center bg-gradient-to-br from-zinc-950 via-zinc-900 to-zinc-950">
      <div className="text-center space-y-6 p-8">
        <h1 className="text-5xl font-bold bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">
          Welcome
        </h1>
        <p className="text-zinc-400 text-lg max-w-md">
          Your application is loading. This page will be replaced with your content.
        </p>
        <div className="flex justify-center gap-4">
          <div className="w-2 h-2 bg-cyan-400 rounded-full animate-pulse" />
          <div className="w-2 h-2 bg-blue-400 rounded-full animate-pulse delay-75" />
          <div className="w-2 h-2 bg-purple-400 rounded-full animate-pulse delay-150" />
        </div>
      </div>
    </main>
  );
}
`;

/**
 * Run all pre-flight checks and auto-fix issues
 */
export function runVisualPreFlight(projectPath: string): PreFlightResult {
  console.log("\n✈️ VISUAL PRE-FLIGHT: Checking critical files...");
  
  const checks: PreFlightCheck[] = [];
  let criticalFixes = 0;
  
  // Determine app directory
  const srcAppPath = path.join(projectPath, 'src', 'app');
  const rootAppPath = path.join(projectPath, 'app');
  const appPath = fs.existsSync(srcAppPath) ? srcAppPath : rootAppPath;
  
  // Ensure app directory exists
  if (!fs.existsSync(appPath)) {
    fs.mkdirSync(appPath, { recursive: true });
    checks.push({
      name: 'App Directory',
      status: 'fixed',
      message: `Created missing app directory: ${appPath}`,
    });
    criticalFixes++;
  }
  
  // Check 1: globals.css
  const globalsPath = path.join(appPath, 'globals.css');
  const globalsCheck = checkGlobalsCss(globalsPath);
  checks.push(globalsCheck);
  if (globalsCheck.status === 'fixed') criticalFixes++;
  
  // Check 2: layout.tsx
  const layoutPath = path.join(appPath, 'layout.tsx');
  const layoutCheck = checkLayout(layoutPath, appPath);
  checks.push(layoutCheck);
  if (layoutCheck.status === 'fixed') criticalFixes++;
  
  // Check 3: page.tsx
  const pagePath = path.join(appPath, 'page.tsx');
  const pageCheck = checkPage(pagePath);
  checks.push(pageCheck);
  if (pageCheck.status === 'fixed') criticalFixes++;
  
  // Check 4: Tailwind config
  const tailwindCheck = checkTailwindConfig(projectPath);
  checks.push(tailwindCheck);
  if (tailwindCheck.status === 'fixed') criticalFixes++;
  
  // Check 5: PostCSS config
  const postcssCheck = checkPostCssConfig(projectPath);
  checks.push(postcssCheck);
  if (postcssCheck.status === 'fixed') criticalFixes++;
  
  // Summary
  const passed = checks.every(c => c.status !== 'fail');
  const passedCount = checks.filter(c => c.status === 'pass').length;
  const fixedCount = checks.filter(c => c.status === 'fixed').length;
  const failedCount = checks.filter(c => c.status === 'fail').length;
  
  console.log(`\n📊 PRE-FLIGHT RESULTS:`);
  console.log(`   ✅ Passed: ${passedCount}`);
  console.log(`   🔧 Auto-fixed: ${fixedCount}`);
  console.log(`   ❌ Failed: ${failedCount}`);
  
  if (fixedCount > 0) {
    console.log(`\n   Fixed issues:`);
    checks.filter(c => c.status === 'fixed').forEach(c => {
      console.log(`      - ${c.name}: ${c.message}`);
    });
  }
  
  return { passed, checks, criticalFixes };
}

function checkGlobalsCss(globalsPath: string): PreFlightCheck {
  if (!fs.existsSync(globalsPath)) {
    fs.writeFileSync(globalsPath, GOLDEN_GLOBALS_CSS);
    return {
      name: 'globals.css',
      status: 'fixed',
      message: 'Created missing globals.css with Tailwind directives',
    };
  }
  
  let content = fs.readFileSync(globalsPath, 'utf-8');
  
  // Check for Tailwind directives
  const hasTailwindBase = content.includes('@tailwind base');
  const hasTailwindComponents = content.includes('@tailwind components');
  const hasTailwindUtilities = content.includes('@tailwind utilities');
  
  if (!hasTailwindBase || !hasTailwindComponents || !hasTailwindUtilities) {
    // Prepend Tailwind directives
    const tailwindDirectives = '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n';
    
    // Remove any existing partial directives
    content = content.replace(/@tailwind\s+(base|components|utilities);?\n?/g, '');
    
    content = tailwindDirectives + content.trim();
    fs.writeFileSync(globalsPath, content);
    
    return {
      name: 'globals.css',
      status: 'fixed',
      message: 'Added missing Tailwind directives',
    };
  }
  
  // Check for obviously broken content (code in CSS)
  if (content.includes('import ') || content.includes('export ') || content.includes('const ')) {
    fs.writeFileSync(globalsPath, GOLDEN_GLOBALS_CSS);
    return {
      name: 'globals.css',
      status: 'fixed',
      message: 'Replaced corrupted globals.css (contained JS code)',
    };
  }
  
  return {
    name: 'globals.css',
    status: 'pass',
    message: 'Valid globals.css with Tailwind directives',
  };
}

function checkLayout(layoutPath: string, appPath: string): PreFlightCheck {
  if (!fs.existsSync(layoutPath)) {
    fs.writeFileSync(layoutPath, GOLDEN_LAYOUT);
    return {
      name: 'layout.tsx',
      status: 'fixed',
      message: 'Created missing layout.tsx',
    };
  }
  
  let content = fs.readFileSync(layoutPath, 'utf-8');
  let modified = false;
  
  // Check for globals.css import
  if (!content.includes('./globals.css') && !content.includes("'./globals.css'") && !content.includes('"./globals.css"')) {
    // Add import after existing imports
    const importMatch = content.match(/^(import\s+.*;\n)+/m);
    if (importMatch) {
      const insertPos = importMatch.index! + importMatch[0].length;
      content = content.slice(0, insertPos) + "import './globals.css';\n" + content.slice(insertPos);
    } else {
      content = "import './globals.css';\n" + content;
    }
    modified = true;
  }
  
  // Check for export default
  if (!content.includes('export default')) {
    fs.writeFileSync(layoutPath, GOLDEN_LAYOUT);
    return {
      name: 'layout.tsx',
      status: 'fixed',
      message: 'Replaced broken layout.tsx (no default export)',
    };
  }
  
  // Check for html/body tags
  if (!content.includes('<html') || !content.includes('<body')) {
    fs.writeFileSync(layoutPath, GOLDEN_LAYOUT);
    return {
      name: 'layout.tsx',
      status: 'fixed',
      message: 'Replaced broken layout.tsx (missing html/body)',
    };
  }
  
  if (modified) {
    fs.writeFileSync(layoutPath, content);
    return {
      name: 'layout.tsx',
      status: 'fixed',
      message: 'Added missing globals.css import',
    };
  }
  
  return {
    name: 'layout.tsx',
    status: 'pass',
    message: 'Valid layout.tsx',
  };
}

function checkPage(pagePath: string): PreFlightCheck {
  if (!fs.existsSync(pagePath)) {
    fs.writeFileSync(pagePath, GOLDEN_PAGE);
    return {
      name: 'page.tsx',
      status: 'fixed',
      message: 'Created missing page.tsx',
    };
  }
  
  const content = fs.readFileSync(pagePath, 'utf-8');
  
  // Check for export default
  if (!content.includes('export default')) {
    fs.writeFileSync(pagePath, GOLDEN_PAGE);
    return {
      name: 'page.tsx',
      status: 'fixed',
      message: 'Replaced broken page.tsx (no default export)',
    };
  }
  
  // Check for empty/minimal content
  if (content.length < 100 || content.includes('return null') || content.match(/<div\s*>\s*<\/div>/)) {
    fs.writeFileSync(pagePath, GOLDEN_PAGE);
    return {
      name: 'page.tsx',
      status: 'fixed',
      message: 'Replaced empty/minimal page.tsx',
    };
  }
  
  // Check for placeholder content
  if (content.includes('// Placeholder') || content.includes('Page skeleton')) {
    // Don't fix - let the AI fill it in
    return {
      name: 'page.tsx',
      status: 'pass',
      message: 'page.tsx exists (placeholder - AI will fill)',
    };
  }
  
  return {
    name: 'page.tsx',
    status: 'pass',
    message: 'Valid page.tsx',
  };
}

function checkTailwindConfig(projectPath: string): PreFlightCheck {
  const configPath = path.join(projectPath, 'tailwind.config.ts');
  const configPathJs = path.join(projectPath, 'tailwind.config.js');
  
  const existingPath = fs.existsSync(configPath) ? configPath : 
                       fs.existsSync(configPathJs) ? configPathJs : null;
  
  const goldenConfig = `import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
      },
    },
  },
  plugins: [],
};

export default config;
`;
  
  if (!existingPath) {
    fs.writeFileSync(configPath, goldenConfig);
    return {
      name: 'tailwind.config',
      status: 'fixed',
      message: 'Created missing tailwind.config.ts',
    };
  }
  
  const content = fs.readFileSync(existingPath, 'utf-8');
  
  // Check for content paths
  if (!content.includes('content:') || !content.includes('./src/')) {
    fs.writeFileSync(configPath, goldenConfig);
    return {
      name: 'tailwind.config',
      status: 'fixed',
      message: 'Fixed tailwind.config (missing src/ content paths)',
    };
  }
  
  return {
    name: 'tailwind.config',
    status: 'pass',
    message: 'Valid tailwind.config',
  };
}

function checkPostCssConfig(projectPath: string): PreFlightCheck {
  const configPath = path.join(projectPath, 'postcss.config.js');
  const configPathMjs = path.join(projectPath, 'postcss.config.mjs');
  
  const existingPath = fs.existsSync(configPath) ? configPath : 
                       fs.existsSync(configPathMjs) ? configPathMjs : null;
  
  const goldenConfig = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;
  
  if (!existingPath) {
    fs.writeFileSync(configPath, goldenConfig);
    return {
      name: 'postcss.config',
      status: 'fixed',
      message: 'Created missing postcss.config.js',
    };
  }
  
  const content = fs.readFileSync(existingPath, 'utf-8');
  
  // Check for tailwindcss plugin
  if (!content.includes('tailwindcss')) {
    fs.writeFileSync(configPath, goldenConfig);
    return {
      name: 'postcss.config',
      status: 'fixed',
      message: 'Fixed postcss.config (missing tailwindcss plugin)',
    };
  }
  
  return {
    name: 'postcss.config',
    status: 'pass',
    message: 'Valid postcss.config',
  };
}

/**
 * Quick check if page looks like it will render properly
 */
export function willPageRender(projectPath: string): boolean {
  const srcAppPath = path.join(projectPath, 'src', 'app');
  const rootAppPath = path.join(projectPath, 'app');
  const appPath = fs.existsSync(srcAppPath) ? srcAppPath : rootAppPath;
  
  const pagePath = path.join(appPath, 'page.tsx');
  const layoutPath = path.join(appPath, 'layout.tsx');
  const globalsPath = path.join(appPath, 'globals.css');
  
  // All critical files must exist
  if (!fs.existsSync(pagePath) || !fs.existsSync(layoutPath) || !fs.existsSync(globalsPath)) {
    return false;
  }
  
  // Page must have default export
  const pageContent = fs.readFileSync(pagePath, 'utf-8');
  if (!pageContent.includes('export default')) {
    return false;
  }
  
  // Layout must import globals.css
  const layoutContent = fs.readFileSync(layoutPath, 'utf-8');
  if (!layoutContent.includes('globals.css')) {
    return false;
  }
  
  // globals.css must have Tailwind
  const globalsContent = fs.readFileSync(globalsPath, 'utf-8');
  if (!globalsContent.includes('@tailwind')) {
    return false;
  }
  
  return true;
}

