/**
 * Pack Podcast Briefs (Night Factory v2.1)
 * Converts Markdown briefs to TXT for NotebookLM upload
 * Creates individual files + combined bundle
 */
import fs from "fs/promises";
import path from "path";

const src = "podcast/briefs";
const outDir = "podcast/export";
await fs.mkdir(outDir, { recursive: true });

console.log("📦 Packing podcast briefs for NotebookLM...");

// Get all markdown files, sorted
const files = (await fs.readdir(src)).filter(f => f.endsWith(".md")).sort();

if (files.length === 0) {
  console.log("⚠️  No briefs found in podcast/briefs/");
  process.exit(0);
}

console.log(`📄 Found ${files.length} brief(s)`);

let combined = "";
const metadata = {
  generated: new Date().toISOString(),
  totalBriefs: files.length,
  briefs: []
};

// Process each brief
for (const f of files) {
  const md = await fs.readFile(path.join(src, f), "utf8");
  const txtName = f.replace(/\.md$/, ".txt");
  const txtPath = path.join(outDir, txtName);
  
  // Add header to individual file
  const header = `Generated by Night Factory
Timestamp: ${new Date().toISOString()}
Source: ${f}

---

`;
  const txtContent = header + md;
  
  await fs.writeFile(txtPath, txtContent, "utf8");
  console.log(`  ✅ ${txtName}`);
  
  // Add to combined file with separator
  combined += `\n\n${"=".repeat(70)}\n`;
  combined += `FILE: ${f}\n`;
  combined += `${"=".repeat(70)}\n\n`;
  combined += md + "\n";
  
  // Track metadata
  metadata.briefs.push({
    filename: txtName,
    sourceFile: f,
    size: Buffer.byteLength(txtContent, "utf8")
  });
}

// Write combined file with header
const combinedHeader = `Night Factory Podcast Briefs Bundle
Generated: ${new Date().toISOString()}
Total Briefs: ${files.length}

This file contains all podcast briefs for easy upload to NotebookLM.
Each brief is separated by a divider for clarity.

${"=".repeat(70)}

`;

await fs.writeFile(
  path.join(outDir, "briefs_all.txt"),
  combinedHeader + combined.trim(),
  "utf8"
);

// Write metadata JSON
await fs.writeFile(
  path.join(outDir, "briefs_metadata.json"),
  JSON.stringify(metadata, null, 2),
  "utf8"
);

console.log(`\n✅ Export complete:`);
console.log(`   - ${files.length} individual TXT files`);
console.log(`   - 1 combined bundle (briefs_all.txt)`);
console.log(`   - Metadata (briefs_metadata.json)`);
console.log(`\n📤 Ready for NotebookLM upload or Google Drive sync`);
