// =============================================================================
// ROOT LAYOUT - FORTRESS FILE (DO NOT MODIFY)
// =============================================================================
// This is a golden template. Regenerate with: npm run generate-fortress

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Frost Night Factory App',
  description: 'Generated by Frost Night Factory',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

