// app/api/pipelines/[id]/env-config/route.ts
import { NextRequest, NextResponse } from 'next/server';
import path from 'node:path';
import fs from 'node:fs/promises';

// ✅ Simple validation (no zod dependency required)
interface EnvConfigBody {
  envValues?: Record<string, string | undefined>;
  demoMode?: boolean;
}

/**
 * Get pipeline workspace path
 * Matches the path structure used in agent-runner/pipeline-runner.ts
 * Path format: agent-runner/workspace/sandbox/pipeline-{id}
 */
function getPipelinePath(pipelineId: string): string {
  // ✅ Use environment variable if set, otherwise resolve relative to project root
  // The agent-runner is typically in the same repo as the Next.js app
  const workspaceRoot = process.env.FROST_WORKSPACE_ROOT || 
                       process.env.AGENT_RUNNER_ROOT ||
                       path.join(process.cwd(), 'agent-runner');
  
  return path.join(
    workspaceRoot,
    'workspace',
    'sandbox',
    `pipeline-${pipelineId}` // Matches agent-runner naming convention
  );
}

/**
 * POST /api/pipelines/[id]/env-config
 * Save environment variable configuration for a pipeline
 */
export async function POST(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const pipelineId = params.id;
    
    if (!pipelineId) {
      return NextResponse.json(
        { ok: false, error: 'Pipeline ID is required' },
        { status: 400 }
      );
    }

    const json: EnvConfigBody = await req.json();
    
    // ✅ Validate and set defaults
    const envValues = json.envValues || {};
    const demoMode = json.demoMode ?? false;
    
    // Validate envValues is an object
    if (typeof envValues !== 'object' || Array.isArray(envValues)) {
      return NextResponse.json(
        { ok: false, error: 'envValues must be an object' },
        { status: 400 }
      );
    }

    const pipelinePath = getPipelinePath(pipelineId);
    const envPath = path.join(pipelinePath, '.env.local');

    // Ensure pipeline directory exists
    await fs.mkdir(pipelinePath, { recursive: true });

    const lines: string[] = [];

    lines.push('# Environment variables for this project');
    lines.push('# Generated by Frost Night Factory env-config API');
    lines.push(`# Pipeline: ${pipelineId}`);
    lines.push(`# Mode: ${demoMode ? 'DEMO' : 'PRODUCTION'}`);
    lines.push('');

    if (demoMode) {
      lines.push('# DEMO MODE: Using placeholder values');
      lines.push('# API calls will not work until you add real keys');
      lines.push('NEXT_PUBLIC_DEMO_MODE=true');
      lines.push('');
    } else {
      lines.push('NEXT_PUBLIC_DEMO_MODE=false');
      lines.push('');
    }

    // Write environment variables
    for (const [key, value] of Object.entries(envValues)) {
      const val = value ?? '';
      
      // ✅ Proper escaping for values with spaces, quotes, special chars
      // If value contains spaces or special chars, wrap in quotes
      if (val.includes(' ') || val.includes('=') || val.includes('"') || val.includes("'")) {
        // Escape quotes and wrap in double quotes
        const escaped = val.replace(/"/g, '\\"');
        lines.push(`${key}="${escaped}"`);
      } else {
        lines.push(`${key}=${val}`);
      }
    }

    const content = lines.join('\n') + '\n';
    await fs.writeFile(envPath, content, 'utf8');

    console.log(`✅ [Env Config] Saved .env.local for pipeline ${pipelineId} (${demoMode ? 'DEMO' : 'PRODUCTION'} mode)`);

    return NextResponse.json({ 
      ok: true, 
      path: envPath,
      demoMode,
      keysConfigured: Object.keys(envValues).length,
    }, { status: 200 });

  } catch (err: any) {
    console.error('❌ [Env Config] Error:', err);
    
    return NextResponse.json(
      { ok: false, error: err.message ?? 'Unknown error' },
      { status: 500 }
    );
  }
}

/**
 * GET /api/pipelines/[id]/env-config
 * Retrieve current environment configuration for a pipeline
 */
export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const pipelineId = params.id;
    
    if (!pipelineId) {
      return NextResponse.json(
        { ok: false, error: 'Pipeline ID is required' },
        { status: 400 }
      );
    }

    const pipelinePath = getPipelinePath(pipelineId);
    const envPath = path.join(pipelinePath, '.env.local');

    // Check if .env.local exists
    try {
      const content = await fs.readFile(envPath, 'utf8');
      
      // Parse .env.local to extract values
      const envValues: Record<string, string> = {};
      let demoMode = false;
      
      const lines = content.split('\n');
      for (const line of lines) {
        const trimmed = line.trim();
        
        // Skip comments and empty lines
        if (!trimmed || trimmed.startsWith('#')) {
          if (trimmed.includes('NEXT_PUBLIC_DEMO_MODE')) {
            demoMode = trimmed.includes('true');
          }
          continue;
        }
        
        // Parse KEY=VALUE
        const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
        if (match) {
          const key = match[1];
          const value = match[2];
          if (!key || value == null) continue;
          // Remove quotes if present
          const unquoted = value.replace(/^["']|["']$/g, '');
          envValues[key] = unquoted;
        }
      }
      
      return NextResponse.json({
        ok: true,
        envValues,
        demoMode,
        path: envPath,
        exists: true,
      });
    } catch (fileError: any) {
      // File doesn't exist yet
      if (fileError.code === 'ENOENT') {
        return NextResponse.json({
          ok: true,
          envValues: {},
          demoMode: false,
          path: envPath,
          exists: false,
        });
      }
      throw fileError;
    }

  } catch (err: any) {
    console.error('❌ [Env Config] GET Error:', err);
    return NextResponse.json(
      { ok: false, error: err.message ?? 'Unknown error' },
      { status: 500 }
    );
  }
}

