-- Create table for storing pipeline memories
create table if not exists night_memories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  prompt text,
  code text,
  embedding vector(1536) -- Förberett för vektor-sök (om du slår på pgvector senare)
);

-- Create index for faster queries
create index if not exists night_memories_created_at_idx on night_memories(created_at desc);
